# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-24 11:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0002_auto_20170908_0822'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='value_de',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='value_it',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
