# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-05 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0003_auto_20171024_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='value_cs',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
