# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conf', '0004_setting_value_cs'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='value_fr',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
