# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-07 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_auto_20171205_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='content_fr',
            field=mezzanine.core.fields.RichTextField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='description_fr',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
    ]
